spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'create-drop'
    show-slq: true

aws:
  bucket:
    name: 'aws-library'
    file: 'database-updates.txt'


